// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyColm1tQuepkswTQscdOsdDICRthJ6QJ0Y',
    appId: '1:707239675439:android:8e75d13bb9f501c4d7a8da',
    messagingSenderId: '707239675439',
    projectId: 'riderapp-47092',
    databaseURL: 'https://riderapp-47092-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riderapp-47092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeKwU1vlhhBg_yRTsLGnMgn7s4vYIX5vM',
    appId: '1:707239675439:ios:ccc817e3e2a4266bd7a8da',
    messagingSenderId: '707239675439',
    projectId: 'riderapp-47092',
    databaseURL: 'https://riderapp-47092-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riderapp-47092.firebasestorage.app',
    iosBundleId: 'com.mighty.taxirider2',
  );
}
